project:
  type: website
engine: knitr
execute:
  freeze: auto  
website:
  title: R to Python cheatsheet
  sidebar:
    style: docked
    contents:
      - index.qmd
      - difference.qmd
format:
  html:
    theme: lumen
    toc: true
    